#pragma once

#include "Components/Sprite/TankSpriteComponent.hpp"
#include "Components/Transform/TankTransformComponent.hpp"
#include "Components/Control/PlayerControlComponent.hpp"
#include "Components/Arena/LevelComponent.hpp"
#include "Components/Sprite/LevelSpriteComponent.hpp"
#include "Components/Collider/TankColliderComponent.hpp"
#include "Components/Tank/TurretComponent.hpp"
#include "Components/Sprite/ProjectileSpriteComponent.hpp"
#include "Components/Transform/ProjectileTransformComponent.hpp"
#include "Components/Tank/ProjectileComponent.hpp"
#include "Components/Arena/HUDComponent.hpp"
#include "Components/Control/AIControlComponent.hpp"
#include "Components/Control/BaseControlComponent.hpp"
#include "Components/Tank/HealthComponent.hpp"